CREATE TABLE audit_log
(
    `_ID`                 bigint AUTO_INCREMENT                                    NOT NULL,
    TENANT_PK             bigint                                      DEFAULT NULL NULL,
    VISIBLE_YN            int                                         DEFAULT 1    NOT NULL,
    HTTP_STATUS           int                                         DEFAULT 0    NULL,
    HTTP_METHOD           tinyint unsigned                                     DEFAULT 0    NULL,
    AGENT_OS              nvarchar(64)   DEFAULT NULL NULL,
    AGENT_OS_VERSION      nvarchar(16)   DEFAULT NULL NULL,
    AGENT_BROWSER         nvarchar(64)   DEFAULT NULL NULL,
    AGENT_BROWSER_VERSION nvarchar(16)   DEFAULT NULL NULL,
    AGENT_DEVICE          nvarchar(128)  DEFAULT NULL NULL,
    REQUEST_URI           nvarchar(256)  DEFAULT NULL NULL,
    REQUEST_IP            numeric(20, 0)                              DEFAULT 0    NULL,
    REQUEST_CONTENT_TYPE  nvarchar(1024) DEFAULT NULL NULL,
    REQUEST_PAYLOAD       longtext  DEFAULT NULL NULL,
    RESPONSE_CONTENT_TYPE nvarchar(32)   DEFAULT NULL NULL,
    RESPONSE_PAYLOAD      longtext  DEFAULT NULL NULL,
    CREATED_DATE          DATETIME                                             NOT NULL,
    USER_PK               bigint                                      DEFAULT NULL NULL,
    USER_ID               nvarchar(128)  DEFAULT NULL NULL,
    USER_EMAIL            nvarchar(128)  DEFAULT NULL NULL,
    USER_NAME             nvarchar(64)   DEFAULT NULL NULL,
    TEAM_PK               bigint                                      DEFAULT NULL NULL,
    TEAM_NAME             nvarchar(128)               NULL,
    MENU_UID              bigint                                      DEFAULT NULL NULL,
    MENU_NAME             nvarchar(128)               NULL,
    API_UID               bigint                                      DEFAULT NULL NULL,
    API_NAME              nvarchar(256)  DEFAULT NULL NULL,
    ERROR_DATA            longtext  DEFAULT NULL NULL,
    CONSTRAINT PK_audit_log__ID PRIMARY KEY (`_ID`)
);